---
version: "3"
services:
  folding-at-home:
    image: gleslie2008/folding-at-home
    container_name: folding-at-home
    environment:
      - USER=Anonymous
      - TEAM=0
      - ENABLE_SMP=true
      - POWER=full
    ports:
      - 7396:7396
      - 36330:36330
    restart: unless-stopped
